//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongNgheWeb_3_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Course
    {
        public tbl_Course()
        {
            this.tbl_Lession = new HashSet<tbl_Lession>();
        }
    
        public int ID { get; set; }
        public string CourseName { get; set; }
        public string CourseImage { get; set; }
        public Nullable<decimal> Pirce { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> TotalView { get; set; }
        public Nullable<int> TotalStudents { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> censored { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CourseDescription { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> SortCourseID { get; set; }
    
        public virtual tbl_Menu tbl_Menu { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual ICollection<tbl_Lession> tbl_Lession { get; set; }
    }
}
