//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongNgheWeb_3_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sort_Course
    {
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string SortCourseName { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
